
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class booking extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
        seat1.addMouseListener(this);
        seat2.addMouseListener(this);
        seat3.addMouseListener(this);
        seat4.addMouseListener(this);
        seat5.addMouseListener(this);
        seat6.addMouseListener(this);
        seat7.addMouseListener(this);
        seat8.addMouseListener(this);
        seat9.addMouseListener(this);
        seat10.addMouseListener(this);
        seat11.addMouseListener(this);
        seat12.addMouseListener(this);
        seat13.addMouseListener(this);
        seat14.addMouseListener(this);
        seat15.addMouseListener(this);
        seat16.addMouseListener(this);
        seat17.addMouseListener(this);
        seat18.addMouseListener(this);
        seat19.addMouseListener(this);
        seat20.addMouseListener(this);
        seat21.addMouseListener(this);
        seat22.addMouseListener(this);
        seat23.addMouseListener(this);
        connect();
        init();
    }
    
    // Thiet lap comboBox
    private void init(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Chọn giờ");
        model.addElement("08:00");
        model.addElement("13:00");
        model.addElement("18:00");
        
        txtcomb.setModel(model);
        
    }
    
    int maghe = 0;
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://localhost/qldatve?user=root&password=y7JE9yRsb!");
            System.out.println("Nối kết thành công");
            
        } catch (SQLException ex) {
            System.out.println("Kết nối không thành công");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Bill(){
        String customer = txtcust.getText();
        int seatcur = maghe;

        SimpleDateFormat date_form = new SimpleDateFormat("yyyy-MM-dd");
        String date = date_form.format(txtcale.getDate());
        
        txtbill.setText(txtbill.getText() + "*************************************\n");
        txtbill.setText(txtbill.getText() + "**************Thông tin vé***********\n\n");
        txtbill.setText(txtbill.getText() + "Tên khách hàng" + "\t" + customer + "\n");
        txtbill.setText(txtbill.getText() + "Số ghế" + "\t\t" + seatcur + "\n");
        txtbill.setText(txtbill.getText() + "Khởi hành lúc" + "\t" + timeValue + " " + date + "\n");
        txtbill.setText(txtbill.getText() + "\n");
        txtbill.setText(txtbill.getText() + "**********^^^^^^^^^^^^^^^^^^^********\n");
        txtbill.setText(txtbill.getText() + "***********Cảm ơn quý khách!*********\n");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcust = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        seat19 = new javax.swing.JLabel();
        seat16 = new javax.swing.JLabel();
        seat15 = new javax.swing.JLabel();
        seat10 = new javax.swing.JLabel();
        seat9 = new javax.swing.JLabel();
        seat4 = new javax.swing.JLabel();
        seat3 = new javax.swing.JLabel();
        seat21 = new javax.swing.JLabel();
        seat17 = new javax.swing.JLabel();
        seat14 = new javax.swing.JLabel();
        seat11 = new javax.swing.JLabel();
        seat8 = new javax.swing.JLabel();
        seat5 = new javax.swing.JLabel();
        seat2 = new javax.swing.JLabel();
        seat23 = new javax.swing.JLabel();
        seat18 = new javax.swing.JLabel();
        seat13 = new javax.swing.JLabel();
        seat12 = new javax.swing.JLabel();
        seat7 = new javax.swing.JLabel();
        seat6 = new javax.swing.JLabel();
        seat1 = new javax.swing.JLabel();
        seat20 = new javax.swing.JLabel();
        seat22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcale = new com.toedter.calendar.JCalendar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtcomb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Đặt vé xe online");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Tên khách hàng");

        txtcust.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        seat19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat19.setText("19");

        seat16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat16.setText("16");

        seat15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat15.setText("15");

        seat10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat10.setText("10");

        seat9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat9.setText("9");

        seat4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat4.setText("4");

        seat3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat3.setText("3");

        seat21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat21.setText("21");

        seat17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat17.setText("17");

        seat14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat14.setText("14");

        seat11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat11.setText("11");

        seat8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat8.setText("8");

        seat5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat5.setText("5");

        seat2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat2.setText("2");

        seat23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat23.setText("23");

        seat18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat18.setText("18");

        seat13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat13.setText("13");

        seat12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat12.setText("12");

        seat7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat7.setText("7");

        seat6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat6.setText("6");

        seat1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat1.setText("1");

        seat20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat20.setText("20");

        seat22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seat22.setText("22");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seat22)
                            .addComponent(seat20))
                        .addGap(0, 259, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat21)
                                .addGap(26, 26, 26)
                                .addComponent(seat17)
                                .addGap(27, 27, 27)
                                .addComponent(seat14)
                                .addGap(26, 26, 26)
                                .addComponent(seat11)
                                .addGap(30, 30, 30)
                                .addComponent(seat8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat19)
                                .addGap(26, 26, 26)
                                .addComponent(seat16)
                                .addGap(27, 27, 27)
                                .addComponent(seat15)
                                .addGap(26, 26, 26)
                                .addComponent(seat10)
                                .addGap(30, 30, 30)
                                .addComponent(seat9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seat23)
                                .addGap(26, 26, 26)
                                .addComponent(seat18)
                                .addGap(27, 27, 27)
                                .addComponent(seat13)
                                .addGap(26, 26, 26)
                                .addComponent(seat12)
                                .addGap(30, 30, 30)
                                .addComponent(seat7)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(seat6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(seat4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(seat3)
                                        .addGap(11, 11, 11)))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(seat1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(seat5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(seat2)))
                                .addGap(19, 19, 19)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat19)
                    .addComponent(seat16)
                    .addComponent(seat15)
                    .addComponent(seat10)
                    .addComponent(seat9)
                    .addComponent(seat4)
                    .addComponent(seat3))
                .addGap(20, 20, 20)
                .addComponent(seat20)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat21)
                    .addComponent(seat17)
                    .addComponent(seat14)
                    .addComponent(seat11)
                    .addComponent(seat8)
                    .addComponent(seat5)
                    .addComponent(seat2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(seat22)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat23)
                    .addComponent(seat18)
                    .addComponent(seat13)
                    .addComponent(seat12)
                    .addComponent(seat7)
                    .addComponent(seat6)
                    .addComponent(seat1))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Chọn ghế");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Chọn thời gian");

        txtcale.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Đặt vé");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtbill.setRows(5);
        jScrollPane1.setViewportView(txtbill);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Kiểm tra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Chọn tầng");

        txtcomb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtcomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(31, 31, 31)
                                    .addComponent(txtcust))
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtcomb, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtcale, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtcomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5))
                    .addComponent(txtcale, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String customer = txtcust.getText();
        String time = timeValue;
        int seatcur = maghe;

        SimpleDateFormat date_form = new SimpleDateFormat("yyyy-MM-dd");
        String date = date_form.format(txtcale.getDate());
        try {
            pst = con.prepareStatement("select * from ve where ngaykh = ? and maghe = ? and giokh = ?");
            pst.setString(1,date);
            pst.setInt(2,seatcur);
            pst.setString(3,time);
            rs = pst.executeQuery();
            
            if(rs.next() == true){
                JOptionPane.showMessageDialog(this, "Ghế đã được đặt\nQuý khách vui lòng chọn ghế khác!");
            }else
            if(customer.length() == 0 || maghe == 0 || timeValue == null){
                JOptionPane.showMessageDialog(this, "Vui lòng cung cấp đầy đủ thông tin");
            }else{
                pst = con.prepareStatement("insert into ve(hoten, maghe, ngaykh, giokh) values (?,?,?,?)");
                pst.setString(1, customer);
                pst.setInt(2, seatcur);
                pst.setString(3, date);
                pst.setString(4, time);
                
                int k =pst.executeUpdate();
                if(k==1){
                    JOptionPane.showMessageDialog(this, "Đặt chỗ thành công");
                    Bill();
                }else{
                    JOptionPane.showMessageDialog(this, "Lỗi hệ thống, quý khách vui lòng thử lại trong giây lát");
                }
              
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        check c = new check();
        c.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    String timeValue;
            
    private void txtcombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcombActionPerformed
        int index = txtcomb.getSelectedIndex();
        if(index > 0){
            timeValue = txtcomb.getItemAt(index);

        }
        
    }//GEN-LAST:event_txtcombActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel seat1;
    private javax.swing.JLabel seat10;
    private javax.swing.JLabel seat11;
    private javax.swing.JLabel seat12;
    private javax.swing.JLabel seat13;
    private javax.swing.JLabel seat14;
    private javax.swing.JLabel seat15;
    private javax.swing.JLabel seat16;
    private javax.swing.JLabel seat17;
    private javax.swing.JLabel seat18;
    private javax.swing.JLabel seat19;
    private javax.swing.JLabel seat2;
    private javax.swing.JLabel seat20;
    private javax.swing.JLabel seat21;
    private javax.swing.JLabel seat22;
    private javax.swing.JLabel seat23;
    private javax.swing.JLabel seat3;
    private javax.swing.JLabel seat4;
    private javax.swing.JLabel seat5;
    private javax.swing.JLabel seat6;
    private javax.swing.JLabel seat7;
    private javax.swing.JLabel seat8;
    private javax.swing.JLabel seat9;
    private javax.swing.JTextArea txtbill;
    private com.toedter.calendar.JCalendar txtcale;
    private javax.swing.JComboBox<String> txtcomb;
    private javax.swing.JTextField txtcust;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        
        if(e.getSource() == seat1){
            maghe = 1;
        }else if(e.getSource() == seat2){
            maghe = 2;
        }else if(e.getSource() == seat3){
            maghe = 3;
        }else if(e.getSource() == seat4){
            maghe = 4;
        }else if(e.getSource() == seat5){
            maghe = 5;
        }else if(e.getSource() == seat6){
            maghe = 6;
        }else if(e.getSource() == seat7){
            maghe = 7;
        }else if(e.getSource() == seat8){
            maghe = 8;
        }else if(e.getSource() == seat9){
            maghe = 9;
        }else if(e.getSource() == seat10){
            maghe = 10;
        }else if(e.getSource() == seat11){
            maghe = 11;
        }else if(e.getSource() == seat12){
            maghe = 12;
        }else if(e.getSource() == seat13){
            maghe = 13;
        }else if(e.getSource() == seat14){
            maghe = 14;
        }else if(e.getSource() == seat15){
            maghe = 15;
        }else if(e.getSource() == seat16){
            maghe = 16;
        }else if(e.getSource() == seat17){
            maghe = 17;
        }else if(e.getSource() == seat18){
            maghe = 18;
        }else if(e.getSource() == seat19){
            maghe = 19;
        }else if(e.getSource() == seat20){
            maghe = 20;
        }else if(e.getSource() == seat21){
            maghe = 21;
        }else if(e.getSource() == seat22){
            maghe = 22;
        }else if(e.getSource() == seat23){
            maghe = 23;
        }
        
        JOptionPane.showMessageDialog(this, "Xác nhận chọn ghế số "+maghe);
            
    }

    @Override
    public void mousePressed(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}